In [1]:
from pathlib import Path
import pandas as pd

In [2]:
current_dir = Path.cwd()

if current_dir.name == "notebooks":
    project_root = current_dir.parent
else:
    project_root = current_dir

data_path = project_root / "data" / "raw" / "Online Retail.xlsx"

print("当前运行目录：", current_dir)
print("项目根目录：", project_root)
print("数据文件路径：", data_path)
print("文件是否存在：", data_path.exists())

当前运行目录： c:\Users\a\Documents\DataAnalysisProjects\ecommerce-customer-analysis\notebooks
项目根目录： c:\Users\a\Documents\DataAnalysisProjects\ecommerce-customer-analysis
数据文件路径： c:\Users\a\Documents\DataAnalysisProjects\ecommerce-customer-analysis\data\raw\Online Retail.xlsx
文件是否存在： True

In [3]:
excel_file = pd.ExcelFile(data_path)
excel_file.sheet_names

['Online Retail']

In [4]:
sample = pd.read_excel(data_path, nrows=10)
sample

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047,United Kingdom

In [5]:
sample.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [6]:
sample.dtypes

InvoiceNo               int64
StockCode              object
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID              int64
Country                   str
dtype: object

## 读取Excel

In [7]:
df_raw = pd.read_excel(
    data_path,
    sheet_name="Online Retail"
)

print("数据读取完成")
print("数据形状：", df_raw.shape)

数据读取完成
数据形状： (541909, 8)

In [8]:
print("行数：", df_raw.shape[0])
print("列数：", df_raw.shape[1])
print("字段：", df_raw.columns.tolist())

df_raw.head(10)

行数： 541909
列数： 8
字段： ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [9]:
df_raw.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [10]:
df_raw.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [11]:
df_raw.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 134.9 MB

## 缺失值检查

In [12]:
missing_summary = pd.DataFrame({
    "missing_count": df_raw.isna().sum(),
    "missing_percent": (df_raw.isna().mean() * 100).round(2)
})

missing_summary.sort_values(
    "missing_count",
    ascending=False
)

             missing_count  missing_percent
CustomerID          135080            24.93
Description           1454             0.27
StockCode                0             0.00
InvoiceNo                0             0.00
Quantity                 0             0.00
InvoiceDate              0             0.00
UnitPrice                0             0.00
Country                  0             0.00

In [13]:
missing_relationship = pd.crosstab(
    df_raw["CustomerID"].isna(),
    df_raw["Description"].isna(),
    rownames=["CustomerID缺失"],
    colnames=["Description缺失"],
    margins=True
)

missing_relationship

Description缺失   False  True     All
CustomerID缺失
False          406829     0  406829
True           133626  1454  135080
All            540455  1454  541909

In [14]:
both_missing_count = (
    df_raw["CustomerID"].isna()
    & df_raw["Description"].isna()
).sum()

print("客户编号和商品描述同时缺失的行数：", both_missing_count)

客户编号和商品描述同时缺失的行数： 1454

## 重复数据检查

In [15]:
exact_duplicate_count = df_raw.duplicated().sum()

print("完全重复行数量：", exact_duplicate_count)
print(
    "完全重复行比例：",
    round(exact_duplicate_count / len(df_raw) * 100, 2),
    "%"
)

完全重复行数量： 5268
完全重复行比例： 0.97 %

In [16]:
duplicate_samples = (
    df_raw[df_raw.duplicated(keep=False)]
    .sort_values(
        ["InvoiceNo", "StockCode", "InvoiceDate"]
    )
)

duplicate_samples.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [17]:
## 核心对象数量

In [19]:
entity_summary = pd.Series({
    "数据行数": len(df_raw),
    "不同订单编号数": df_raw["InvoiceNo"].nunique(dropna=True),
    "不同商品编号数": df_raw["StockCode"].nunique(dropna=True),
    "不同客户数": df_raw["CustomerID"].nunique(dropna=True),
    "不同国家或地区数": df_raw["Country"].nunique(dropna=True)
})

entity_summary

数据行数        541909
不同订单编号数      25900
不同商品编号数       4070
不同客户数         4372
不同国家或地区数        38
dtype: int64

In [ ]:
## 时间范围检查

In [20]:
date_summary = df_raw["InvoiceDate"].agg(
    ["min", "max"]
)

date_summary

min   2010-12-01 08:26:00
max   2011-12-09 12:50:00
Name: InvoiceDate, dtype: datetime64[us]

In [21]:
print(
    "覆盖天数：",
    (
        df_raw["InvoiceDate"].max()
        - df_raw["InvoiceDate"].min()
    ).days
)

覆盖天数： 373

## 数量与价格检查

In [22]:
df_raw[["Quantity", "UnitPrice"]].describe(
    percentiles=[0.01, 0.25, 0.5, 0.75, 0.99]
).T

,count,mean,std,min,1%,25%,50%,75%,99%,max
Quantity,541909.0,9.552250,218.081158,-80995.00,-2.00,1.00,3.00,10.00,100.0,80995.0
UnitPrice,541909.0,4.611114,96.759853,-11062.06,0.19,1.25,2.08,4.13,18.0,38970.0

In [23]:
numeric_check = pd.Series({
    "Quantity小于0": (df_raw["Quantity"] < 0).sum(),
    "Quantity等于0": (df_raw["Quantity"] == 0).sum(),
    "Quantity大于0": (df_raw["Quantity"] > 0).sum(),
    "UnitPrice小于0": (df_raw["UnitPrice"] < 0).sum(),
    "UnitPrice等于0": (df_raw["UnitPrice"] == 0).sum(),
    "UnitPrice大于0": (df_raw["UnitPrice"] > 0).sum()
})

numeric_check

Quantity小于0      10624
Quantity等于0          0
Quantity大于0     531285
UnitPrice小于0         2
UnitPrice等于0      2515
UnitPrice大于0    539392
dtype: int64

In [26]:
max_and_min = pd.Series({
    "Quantity最小值": df_raw["Quantity"].min(),
    "Quantity最大值：": df_raw["Quantity"].max(),
    "UnitPrice最小值：": df_raw["UnitPrice"].min(),
    "UnitPrice最大值：": df_raw["UnitPrice"].max()
}
)

max_and_min

Quantity最小值     -80995.00
Quantity最大值：     80995.00
UnitPrice最小值：   -11062.06
UnitPrice最大值：    38970.00
dtype: float64

## 取消订单检查

In [27]:
invoice_text = (
    df_raw["InvoiceNo"]
    .astype("string")
    .str.strip()
)

is_cancelled = invoice_text.str.upper().str.startswith(
    "C",
    na=False
)

is_negative_quantity = df_raw["Quantity"] < 0

In [28]:
cancellation_check = pd.Series({
    "订单编号以C开头的记录": is_cancelled.sum(),
    "C开头且数量为负": (
        is_cancelled & is_negative_quantity
    ).sum(),
    "C开头但数量非负": (
        is_cancelled & ~is_negative_quantity
    ).sum(),
    "数量为负但订单号不以C开头": (
        ~is_cancelled & is_negative_quantity
    ).sum()
})

cancellation_check

订单编号以C开头的记录      9288
C开头且数量为负         9288
C开头但数量非负            0
数量为负但订单号不以C开头    1336
dtype: int64

In [29]:
negative_without_c = df_raw.loc[
    ~is_cancelled & is_negative_quantity,
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

negative_without_c.head(20)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,0.0,NaN,United Kingdom

In [30]:
negative_without_c[
    ["StockCode", "Description"]
].value_counts(dropna=False).head(20)

StockCode  Description
21161      NaN            3
22162      NaN            3
22034      NaN            3
20966      NaN            3
20892      NaN            3
84631      NaN            3
22114      NaN            3
85017A     NaN            3
72802C     check          3
72802B     check          3
22028      NaN            2
85067      NaN            2
21414      NaN            2
85126      NaN            2
21692      NaN            2
21172      NaN            2
84534B     NaN            2
21040      NaN            2
37464      NaN            2
21836      NaN            2
Name: count, dtype: int64

In [31]:
non_positive_price = df_raw.loc[
    df_raw["UnitPrice"] <= 0,
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

non_positive_price.head(20)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,0.0,NaN,United Kingdom

In [32]:
df_raw.loc[
    df_raw["UnitPrice"] < 0,
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom

In [33]:
stock_text = (
    df_raw["StockCode"]
    .astype("string")
    .str.strip()
)

is_standard_stock = stock_text.str.fullmatch(
    r"\d{5}[A-Za-z]?",
    na=False
)

print("标准形式商品编码数量：", is_standard_stock.sum())
print("非标准形式商品编码数量：", (~is_standard_stock).sum())

标准形式商品编码数量： 538524
非标准形式商品编码数量： 3385

In [34]:
special_stock_summary = (
    df_raw.loc[
        ~is_standard_stock,
        ["StockCode", "Description"]
    ]
    .value_counts(dropna=False)
    .head(30)
)

special_stock_summary

StockCode     Description
POST          POSTAGE                               1252
DOT           DOTCOM POSTAGE                         709
M             Manual                                 571
15056BL       EDWARDIAN PARASOL BLACK                326
C2            CARRIAGE                               143
D             Discount                                77
S             SAMPLES                                 63
15056bl       EDWARDIAN PARASOL BLACK                 62
BANK CHARGES  Bank Charges                            37
AMAZONFEE     AMAZON FEE                              34
CRUK          CRUK Commission                         16
DCGSSGIRL     GIRLS PARTY BAG                         13
DCGSSBOY      BOYS PARTY BAG                          11
gift_0001_20  Dotcomgiftshop Gift Voucher £20.00       9
gift_0001_10  Dotcomgiftshop Gift Voucher £10.00       8
gift_0001_30  Dotcomgiftshop Gift Voucher £30.00       7
DCGS0003      BOXED GLASS ASHTRAY                      4
gift_0001_50  Dotcomgiftshop Gift Voucher £50.00       4
POST          NaN                                      4
PADS          PADS TO MATCH ALL CUSHIONS               4
gift_0001_40  Dotcomgiftshop Gift Voucher £40.00       3
B             Adjust bad debt                          3
DCGS0076      SUNJAR LED NIGHT NIGHT LIGHT             2
DCGS0070      CAMOUFLAGE DOG COLLAR                    1
m             Manual                                   1
DCGS0055      NaN                                      1
DCGS0072      NaN                                      1
DCGS0074      NaN                                      1
DCGS0069      OOH LA LA DOGS COLLAR                    1
DCGS0057      NaN                                      1
Name: count, dtype: int64

In [35]:
country_summary = (
    df_raw
    .groupby("Country", dropna=False)
    .agg(
        record_count=("InvoiceNo", "size"),
        invoice_count=("InvoiceNo", "nunique"),
        customer_count=("CustomerID", "nunique")
    )
    .sort_values(
        "record_count",
        ascending=False
    )
)

country_summary.head(10)

                record_count  invoice_count  customer_count
Country
United Kingdom        495478          23494            3950
Germany                 9495            603              95
France                  8557            461              87
EIRE                    8196            360               3
Spain                   2533            105              31
Netherlands             2371            101               9
Belgium                 2069            119              25
Switzerland             2002             74              21
Portugal                1519             71              19
Australia               1259             69               9

In [36]:
assert df_raw.shape == (541909, 8)
assert df_raw.columns.tolist() == [
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country"
]

print("原始DataFrame结构保持不变")

原始DataFrame结构保持不变